#!/bin/sh /etc/rc.common
START=41
USE_PROCD=1

MTD_NUM="7"
VOL_SIZE="12MiB"
VOL_NAME="oneip_log"

MTD_DEV="mtd${MTD_NUM}"
UBI_DEV=""		# Dynamic assign
MOUNT_POINT="/mnt/${VOL_NAME}"

start_service() {
    if ! ubiattach /dev/ubi_ctrl -m $MTD_NUM 2>/dev/null; then
        echo "UBI not formatted on $MTD_DEV, formatting..."
        ubiformat /dev/$MTD_DEV -y
        ubiattach /dev/ubi_ctrl -m $MTD_NUM
    else
        echo "$MTD_DEV is already UBI formatted"
    fi

	for ubi in /sys/class/ubi/ubi*; do
		if [ -d "$ubi" ]; then
			if grep -q "^$MTD_NUM$" "$ubi/mtd_num" 2>/dev/null; then
				UBI_DEV=$(basename "$ubi")
				break
			fi
		fi
	done

	if [ -z "$UBI_DEV" ]; then
		echo "Failed to detect UBI device for mtd$MTD_NUM"
		exit 1
	fi
	echo "Detected UBI device: $UBI_DEV"

	if ! ubinfo /dev/$UBI_DEV -a 2>/dev/null | grep -q "Name:.*$VOL_NAME"; then
		echo "Creating volume $VOL_NAME on $UBI_DEV..."
		ubirmvol /dev/$UBI_DEV -n 0
		ubimkvol /dev/$UBI_DEV -N $VOL_NAME -s $VOL_SIZE
	fi

	mkdir -p $MOUNT_POINT
	mount -t ubifs ${UBI_DEV}_0 $MOUNT_POINT
}

stop_service() {
    umount $MOUNT_POINT 2>/dev/null
    ubidetach -m $MTD_NUM 2>/dev/null
}

