#!/bin/sh /etc/rc.common

START=44
USE_PROCD=1

start_service() {
	SRC="/tmp/system.log"
	DEST="/mnt/oneip_log/systemLOG_temp.log"
	MOUNT_POINT="/mnt/oneip_log"

	if ! mountpoint -q "$MOUNT_POINT"; then
		logger -t watch_log_sync "Mount point $MOUNT_POINT not ready"
		exit 1
	fi

	touch /var/lib/logrotate.status

	# Assign instance name
	procd_open_instance "watch_log_sync"
	procd_set_param command /usr/sbin/systemLogSync.sh
	procd_set_param respawn
	procd_close_instance
}

