#!/bin/sh /etc/rc.common
START=43
USE_PROCD=1
start_service() {
	SRC="/tmp/system.log"
	DEST="/mnt/oneip_log/systemLOG_temp.log"
	MOUNT_POINT="/mnt/oneip_log"
	if ! mountpoint -q "$MOUNT_POINT"; then
		logger -t watch_log_sync "Mount point $MOUNT_POINT not ready"
		exit 1
	fi
	procd_open_instance
	procd_set_param command /bin/sh -c "
		inotifywait -m $SRC -e modify | while read; do
			if [ -f $SRC ]; then
				cp $SRC $DEST
				sync
			fi
		done"
	procd_set_param respawn
	procd_close_instance
}

